### ISSUE TITLE
Test deploy in vagrant image

### ISSUE THREAD

**Issue by cybersiddhu** [dictybase-docker/frontpage#6]
#1

**Comment by biodavidjm** [comment]
Tests of `docker-compose` so far:
- FAIL: vagrant box `chef/centos-7.0`
- SUCCESS: works on Mac. 
- SUCCESS on the "docker-friendly" VAGRANT box `phusion/ubuntu-14.04-amd64`

**Comment by cybersiddhu** [comment]
Did the ansible deploy works.

**Comment by biodavidjm** [comment]
Not yet Sidd. Struggling and going back to make sure that docker compose works first. Keep tryin

**Comment by biodavidjm** [comment]
Not yet Sidd. Struggling. Went back to make sure docker-compose was working first. I'll keep trying my best. I let you know when I'll make it work

**Comment by cybersiddhu** [comment]
All you need is to create two text files and the instructions are clearly given. So, what exactly seemed to be the problem. Please provide detail feedback of your struggle.

**Comment by biodavidjm** [comment]
---

###### DOUBTS (trying to clarify)

* For the local vagrant machine, should we use the [`Vagrantfile`](https://github.com/dictybase-docker/ansible-frontpage/blob/master/Vagrantfile) available in the project?
* Trying to understand how to use the `dicty-local` group. Should a `dicty-local` group being created through the [Vagrantfile](http://docs.vagrantup.com/v2/synced-folders/basic_usage.html) to access the `group_vars` folder?
* Regarding the `ansible_ssh_private_key_file` key, the files available at `.vagrant/machines/default/virtualbox/` are:

```shell
action_provision 
action_set_name  
id               
index_uuid       
private_key      
synced_folders
```
Is the `private_key` value what should be added to `ansible_ssh_private_key_file=`? or is `id`?

* Where is the `group_vars` folder created? in the root of this current project? I am confused by the fact that it is not already available. I see it is ignore in the `.gitignore` file but not sure why if the details of the configuration are given in the readme file.

---

**Comment by cybersiddhu** [comment]
* For the local vagrant machine, should we use the [`Vagrantfile`](https://github.com/dictybase-docker/ansible-frontpage/blob/master/Vagrantfile) available in the project?
Yes, that's why you have the vagrant file.

* Trying to understand how to use the `dicty-local` group. Should a `dicty-local` group being created through the [Vagrantfile](http://docs.vagrantup.com/v2/synced-folders/basic_usage.html) to access the `group_vars` folder? If so... why is not already available in the file? (it confuses me). Should this parameter being added to the `Vagrantfile`:
```shell
  config.vm.synced_folder "/whatever/ansible-frontpage/group_vars/", "/vagrant",
    owner: "vagrant", group: "centos7"
```
No it should not. It is not available because the `hosts` file will contain ip address of remotes hosts which we cannot commit to public repository.

* Regarding the `ansible_ssh_private_key_file` key, the files available at `.vagrant/machines/default/virtualbox/` are:

```shell
action_provision 
action_set_name  
id               
index_uuid       
private_key      
synced_folders
```
Is the `private_key` value what should be added to `ansible_ssh_private_key_file=`? or is `id`?

  It is `private_key`. 


* Where is the `group_vars` folder created? in the root of this current project? I am confused by the fact that it is not already available. I see it is ignore in the `.gitignore` file but not sure why if the details of the configuration are given in the readme file.

The error I get when running `ansible-playbook`:

```shell
ERROR: cannot find role in /whatever/ansible-frontpage/roles/common or /whatever/ansible-frontpage/common or /etc/ansible/roles/common
```

 It is clearly written in README file. I don't know how else i could write that. I also assumed you have done background reading on ansible documentation which from your questions seems to be not the case. The group_vars should be in the same folder.
Also the shell commands ...
```
mkdir group_vars
touch group_vars/dicty_local
```
says what it does. What part of it is not clear here ? Have you tried ? I would really like to know seriously.

followed by the line
```
docker_user: vagrant
image: centos7
```

tells you the configuration of group_vars. What part of it is not clear here ?
Have you tried to create a group_vars file and deploy that ? What happened when you tried to do that ?



---

**Comment by biodavidjm** [comment]
>mkdir group_vars
>touch group_vars/dicty_local
>says what it does. What part of it is not clear here ? Have you tried ? I would really like to know seriously.

Please, double check my comment. I didn't ask anything about it, just where the folder had to be created, Sidd. This part is very clear to me.

> Have you tried to create a group_vars file and deploy that ? What happened when you tried to do that ?

I am extraordinarily sorry Sidd. You asked why I am struggling and I tried to reply your question. I am struggling because the documentation about `ansible` is not very clear to me. I don't get it. I am getting lost in the documentation. I just need to keep trying until I get it.

So far, I think I have done everything that it is said in the `readme` file and I am still getting the same error:

```shell
ERROR: cannot find role in /.../ansible-frontpage/roles/common or /.../ansible-frontpage/common or /etc/ansible/roles/common
```
I don't know why. But please, give me some time and I'll try to understand what the problem is. Thanks anyway, your comments are always very helpful.

**Comment by cybersiddhu** [comment]
:disappointed: 
No problem, lets drop ansible altogether, because i think this one is the easiest to use so far among what's available and the documentation is really good.  For example, just googling for `group_vars` gives me this nice link
http://rosstuck.com/multistage-environments-with-ansible/
As always, if you get stuck, open a demo/toy project and try it out there. There are plenty of github projects and blogs in the internet that will help you to that in minutes. 
 However, that not seems to be happening here and moreover the problem is we are time constrained.
So, i am going for alternative
* Provide you with a centos vagrant vm that have docker preinstalled. I think that could be shared through vagrant cloud.
* Deploy docker directly to remote host using secure socker(tls). What you have to do is to learn how to run a secure client as described [here](https://docs.docker.com/articles/https/). Remember, you only have to do the client part. Yes and as usual i will write the documentation.

If that does not work with you, that will be the end of any kind of deployment.  :-1:

**Comment by biodavidjm** [comment]
I am very sorry to disappoint you Sidd. I haven't spent enough time with ansible yet.
Anyway, I am 100% sure that whatever option you like better for deployment it will work. I hope we can discuss all this in person one of these days.

**Comment by cybersiddhu** [comment]
Please go ahead start learning whatever it needs for you get things done. If you have any question, just schedule up a time when you would like to talk and we can chat over skype.
